.travis.yml
README.md

When puppetlabs/wash is tagged, will build `wash` binaries for macOS and Linux and include them with the release.

Add deployment stage to build and deploy wash releases

---

api/cache_test.go
fuse/dir.go
fuse/file.go
plugin/aws/ec2Dir.go
plugin/aws/ec2Instance.go
plugin/aws/profile.go
plugin/aws/resourcesDir.go
plugin/aws/root.go
plugin/aws/s3Object.go
plugin/cache.go
plugin/cache_test.go
plugin/docker/root.go
plugin/docker/volume.go
plugin/entryBase.go
plugin/entryBase_test.go
plugin/externalPluginEntry.go
plugin/externalPluginEntry_test.go
plugin/externalPluginRoot.go
plugin/externalPluginRoot_test.go
plugin/helpers.go
plugin/helpers_test.go
plugin/kubernetes/pvc.go
plugin/kubernetes/root.go
plugin/registry.go
plugin/types.go
volume/dir.go
volume/file.go

This commit removes CacheConfig by embedding its methods in the Entry
interface. Doing so makes the code easier to read and maintain because
it avoids passing around a CacheConfig pointer, and it structurally
captures the fact that all entries have cacheable operations.
Additionally, this commit makes plugin.Entry a sealed interface,
which forces internal plugin authors to use plugin.NewEntry when
creating their objects.

Embed CacheConfig in the Entry interface

---

.travis.yml
cmd/root.go
cmd/version.go

Lists the current version. Version is set with `go build -ldflags="-X
github.com/puppetlabs/wash/cmd.version=${VERSION}"` as part of tagged
builds.
Resolves #144.

Add version command

---

plugin/cache.go
plugin/cache_test.go
plugin/entryBase.go
plugin/entryBase_test.go
plugin/externalPluginEntry_test.go
plugin/helpers_test.go
plugin/registry.go
plugin/types.go

This commit adds plugin.CachedOp. Plugin authors can use this method
when they need more fine-grained caching than is provided by the
existing CachedList, CachedOpen, and CachedMetadata methods.
This commit also does some small cleanup of the code, specifically:
* plugin.NewEntry now validates that the provided name is non-empty and
that it does not contain a "/". If this validation fails, then Wash will
panic.
* All of the plugin.Cached* methods will panic if entry.ID() is empty
(i.e. if the entry's ID was not set).
* As a consequence of ^, plugin.Registry's ID is now set to "/" instead
of the empty string. This makes more sense since plugin.Registry
represents Wash's root.
Resolves https://github.com/puppetlabs/wash/issues/123

Add plugin.CachedOp

---

api/client/client.go
api/types/error.go
cmd/root.go
cmd/util/format.go
config/core.go
datastore/cache.go
docs/external_plugins/README.md
fuse/core.go
journal/core.go
plugin/aws/root.go
plugin/docker/root.go
plugin/kubernetes/root.go
plugin/types.go
volume/helpers.go
wash.go

Improves the landing page for external plugins docs.
Adds package-level documentation to provide useful context for starting to improve documentation in individual packages.
Resolves #148.

Better docs

---

cmd/server.go
docs/external_plugins/README.md
plugin/action.go
plugin/entryBase_test.go
plugin/externalPluginEntry.go
plugin/externalPluginEntry_test.go
plugin/externalPluginRoot.go
plugin/externalPluginRoot_test.go
plugin/externalPluginScript.go
plugin/helpers.go
plugin/registry.go
plugin/registry_test.go
plugin/testdata/external.sh

The external plugin implementation is an implementation detail in wash,
it should not be exported from the package. Make most of the
implementation private. Leaves RegisterExternalPlugin (and
ExternalPluginSpec) public to allow the CLI to augment the registry.

Make external plugin implementation private

---

plugin/aws/s3Bucket.go
plugin/entryBase.go

Entries can no longer contain '/', and listing it as a subdirectory
would be redundant (its contents are already listed in the base s3
directory).
Fixes #152.

Skip the '/' common prefix for S3 buckets

---

plugin/aws/s3Dir.go

The S3 API will not return a LocationConstraint for a bucket hosted in
its default region, US East (N. Virginia) aka us-east-1. Explicitly use
this region when no LocationConstraint is returned.
Fixes #153.

Default region to us-east-1 when not specified

---

cmd/ps.go
plugin/docker/container.go

When exec included input, Docker exec would hang. This was a regression introduced with commit e5f8c80, where it removed closing the write stream after copying input. Restore the call to `CloseWrite` so that `wash ps` works again on Docker containers.
Also fix ps when multiple processes are present on the target.

Fixes for ps

---

.travis.yml
README.md
plugin/aws/ec2Instance.go
plugin/docker/volume.go
plugin/kubernetes/pvc.go

Tar and gzip builds for release to shrink size to ~28% of uncompressed size for hosting/downloads. This also preserves the executable bit and allows us to leave the executable named `wash` after unpacking.

Add goreportcard badge and shrink release packages

---

api/server.go
config/core.go

Previously it defaulted to creation in `/tmp`, which is usually readable
by anyone on the system. Since access to the API server often grants
admin privileges to execute commands over any configured plugins, move
the socket to a secure location: the UserCacheDir.

Move the mounted API socket to a secure path

---

plugin/aws/s3Bucket.go
plugin/aws/s3Dir.go

Querying the region for every bucket when listing available buckets
results in many queries to list them. We only need the region when we're
listing the contents of the bucket. Delay getting the region name until
we need it.
The region result will be cached indefinitely. If there's an error,
delete the cache entry for the bucket to force a retry.
This saves ~4 seconds for listing an s3 account with ~180 buckets. It
now takes ~4 seconds to do the initial listing, then ~100ms for each
subsequent listing when the cache expires.

Delay getting region for bucket

---

plugin/aws/s3Bucket.go

CachedOp panics if given a negative TTL. Use a long positive TTL instead
to accomplish a similar goal. Fixes a regression introduced by #170.

Use a positive TTL for CachedOp

---

README.md
plugin/aws/fileCacheProvider.go
plugin/aws/profile.go
plugin/aws/root.go

Adds support for IAM Roles when configured according to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html.
Includes file caching of credentials requested with MFA, and uses that to prompt for credentials on startup and cache them for later sessions.
Credentials retrieved currently last 15 minutes. See aws/aws-sdk-go#2532 for discussion of why we haven't modified that yet.
Known issue: `region` is not correctly inherited from the `source_profile`.
Resolves #168.

Add support for IAM Roles

---

plugin/aws/root.go

According to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html, `config` and `credentials` files have different naming formats. Trim `profile ` from names in `config` to allow them to match names in `credentials`.

Trim 'profile ' from config names

---

plugin/aws/fileCacheProvider.go
plugin/aws/profile.go
plugin/aws/root.go

Also allow auth to fail while still loading remaining profiles. A common
case where profiles fail are when loading multiple roles for the same
account, where the same MFA token needs to be used but AWS requires that
each login use a different iteration of the token.
Remove caching messages that didn't provide actionable output to make
logs clearer.

Make AWS credential errors more helpful

---

fuse/core.go
fuse/dir.go
fuse/file.go

This ensures that all of our FUSE methods write to the right journal
regardless of whether the PID's included in the method's request.

Create FUSE server obj, configure it to pass-in the PID

---

plugin/aws/ec2Instance.go

This was previously turned off because the instances' metadata.json and
console output files were stored as struct fields. However, the
attributes-metadata work moved those over to List. That work should have
re-enabled caching since entry attributes are now refreshed via a call
to the parent's CachedList.

Enable caching for an EC2 instance

---

cmd/server.go
fuse/core.go
fuse/dir.go
fuse/file.go
journal/core.go
journal/core_test.go
plugin/aws/ec2Instance.go
plugin/aws/ec2InstanceConsoleOutput.go
plugin/aws/s3Bucket.go
plugin/aws/s3Object.go
plugin/cache.go
plugin/cache_test.go
plugin/kubernetes/pod.go

Move to nanosecond granularity logging to debug slow operations.
Consistently print the journal ID for logged actions, and write all FUSE
activity to the journal.

Improve debugging using activity journal

---

api/cache_test.go
datastore/cache.go
datastore/cache_test.go
journal/core.go
plugin/aws/ec2Instance.go
plugin/cache.go
plugin/cache_test.go

Allow cached lookup of one category within a cached lookup of a different category of call to work without deadlock. Fixes an issue where CachedList would call cachedDescribeInstance in ec2Instance and sometimes deadlock trying to use the same mutex.
Also avoid caching MetadataOp on ec2InstanceMetadataJSON unnecessarily.

Fix deadlock

---

fuse/dir.go
plugin/cache.go
plugin/cache_test.go

For new entries created in a call to CachedList - which should be all of them - enable creating an ID as-needed by adding the parent ID to the context to be used by those cached operations. This should avoid any scenario where we can't determine a cache ID.
Also remove prefetching. It's mostly not needed and creates lots of implicit traffic that can
slow the rest of the experience. There are some scenarios where prefetching improved responsiveness, but it was equally likely to exceed rate limits on APIs and cause errors.
We could explore re-adding it with something like https://gobyexample.com/worker-pools (and maybe rate limiting) to limit concurrent requests so local responsiveness when not immediately using the prefetched data isn't impacted and to avoid running into rate limiting on …

Ensure new entries always have an ID

---

cmd/server.go
journal/helper.go

Looking up process name based on ID was taking more time than satisfying the request from the process. Cache mapping process ID to name to greatly speed that up.
Also include code necessary to do cpu profiling.

Cache resolving process ID to name

---

README.md

This moves the community interaction section higher in the doc to encourage more people to get involved.

Move the community interaction higher in the doc

---

go.mod
go.sum
plugin/aws/profile.go

Reduces the frustration of re-entering your MFA token every 15 minutes. IAM allows configuring a limit on accounts from 1 to 12 hours. Chose 1 hour as the minimum limit so all accounts work. We should later make it configurable so those with longer limits can use them.
Explore https://github.com/posilva/go-mfa and https://github.com/AlexRudd/mfa later for additional improvements such as bulk role assumption and automatically generating tokens from the MFA key.
Remove the go.mod replace statement once https://github.com/aws/aws-sdk-go/pull/2554 is merged.

Increase duration of AWS session tokens that require MFA to 1 hour

---

cmd/ps.go
plugin/aws/ec2Instance.go

For instances using the `dash` shell in EC2, shell escaping didn't work
right for tabs, newlines, and null characters as they'd be replaced by
their literal values after echoing. Escape those characters.
Some processes also have an empty cmdline file. Handle those cases.

Fix ps on some AWS instances

---

cmd/find/sizePrimary.go
cmd/find/sizePrimary_test.go
cmd/find/timeAttrPrimary.go
cmd/find/timeAttrPrimary_test.go

The size primary was modeled off its counterpart in BSD's `find`
command.

Add the size primary to `wash find`

---

api/helpers.go
api/helpers_test.go
cmd/list.go
cmd/root.go

Renames the `wash ls` command to `wash list` to make it more consistent with the API. Also includes `wash ls` as an alias to `wash list` to preserve familiarity with the `ls` command.
Fixes listing
- files
- the wash root directory
- wash plugin roots
Also simplifies code around listing the current directory, and introduces a foundation for listing non-resource paths.
Updates `wash list` to work for normal files and directories. Emits similar table content to that used for wash resources.
Resolves #204.

Improve wash ls subcommand

---

api/client/client.go
api/error.go
api/helpers.go
api/helpers_test.go
api/info.go
api/list.go
api/server.go
api/types/error.go
cmd/clear.go
cmd/exec.go
cmd/find.go
cmd/list.go
cmd/meta.go
cmd/ps.go
cmd/server.go
cmd/tail.go
fuse/core.go
fuse/file.go
plugin/cache.go
plugin/cache_test.go
plugin/helpers.go
plugin/helpers_test.go

This removes the dependency on xattr for determining the API key. It
also paves the way for the API to support regular files/directories
(i.e. non-Wash entries) in subsequent commits.

Require absolute paths for the Wash API

---

api/error.go
api/fs/core.go
api/fs/dir.go
api/fs/file.go
api/helpers.go
api/helpers_test.go
api/types/error.go
cmd/list.go
cmd/tail.go
plugin/cache.go
plugin/cache_test.go
plugin/helpers.go
plugin/helpers_test.go

This commit adds the apifs package, which is used by the API to convert
local files/directories into Wash entries. This means that custom commands
built on the API are no longer required to special-case on them.

Extend Wash API to support local files and directories

---

api/error.go
api/types/error.go

Make error messages more readable by formatting them client-side.
Previously they would print out the serialized JSON, which is difficult
to read.

Prettify error messages

---

api/exec.go
api/stream.go
api/types/exec.go
plugin/aws/s3Object.go
plugin/cleanupReader.go
plugin/cleanupReader_test.go
plugin/docker/container-log.go
plugin/docker/container.go
plugin/docker/volume.go
plugin/externalPluginEntry.go
plugin/kubernetes/pod.go
plugin/kubernetes/pvc.go
plugin/outputStream.go
plugin/outputStream_test.go
plugin/types.go
volume/core.go
volume/dir_test.go
volume/file.go
volume/file_test.go
volume/fs.go
volume/fs_test.go

Add Stream support to the volume package. Add Tty support to Exec on Docker and Kubernetes to support correctly cleaning up processes after terminating streaming.
Resolves #227.

Stream logs from VMs

---

cmd/internal/find/parser/parseExpression_test.go
cmd/internal/find/parser/parsertest/suite.go
cmd/internal/find/primary/meta/arrayPredicate_test.go
cmd/internal/find/primary/meta/emptyPredicate_test.go
cmd/internal/find/primary/meta/numericPredicate_test.go
cmd/internal/find/primary/meta/objectPredicate_test.go
cmd/internal/find/primary/meta/predicate_test.go
cmd/internal/find/primary/meta/primitivePredicate_test.go
cmd/internal/find/primary/meta/stringPredicate_test.go
cmd/internal/find/primary/meta/timePredicate_test.go

When parserTestSuite was added, it introduced importing the `testing`
package (via testify) outside of a test context. That caused the
`test.v` flag to be defined, so initializing the cache in normal
operations (running `wash server`) failed.
Move the parser suite test helpers to their own package that's only used
during testing to avoid this problem.

Move parser suite test helpers to a separate package

---

.travis.yml

When tagging a release, the build is triggered for branch=<tag>, not
branch=master. Our previous conditional for the deploy stage expected
branch=master so it didn't run for the release. Update the stage to run
whenever a tag is present.

Fix stage condition

---

README.md
docs/index.html
website/content/_index.md

Screencast generated with asciinema in a 100x20 frame to best fit the
website and README previow. README links to a larger version that looks
better as a full-size video.
Resolves #238.

Add screencast to website and README

---

cmd/internal/find/parser/expression/parser.go
cmd/internal/find/parser/parseExpression_test.go
cmd/internal/find/parser/predicate/parser.go
cmd/internal/find/primary/meta.go
cmd/internal/find/primary/meta/arrayPredicate.go
cmd/internal/find/primary/meta/arrayPredicate_test.go
cmd/internal/find/primary/meta/emptyPredicate.go
cmd/internal/find/primary/meta/emptyPredicate_test.go
cmd/internal/find/primary/meta/expression.go
cmd/internal/find/primary/meta/numericPredicate.go
cmd/internal/find/primary/meta/numericPredicate_test.go
cmd/internal/find/primary/meta/objectPredicate.go
cmd/internal/find/primary/meta/objectPredicate_test.go
cmd/internal/find/primary/meta/parse.go
cmd/internal/find/primary/meta/predicate.go
cmd/internal/find/primary/meta/predicateExpression.go
cmd/internal/find/primary/meta/predicateExpression_test.go
cmd/internal/find/primary/meta/predicate_test.go
cmd/internal/find/primary/meta/primitivePredicate.go
cmd/internal/find/primary/meta/primitivePredicate_test.go
cmd/internal/find/primary/meta/stringPredicate.go
cmd/internal/find/primary/meta/stringPredicate_test.go
cmd/internal/find/primary/meta/timePredicate.go
cmd/internal/find/primary/meta/timePredicate_test.go
cmd/internal/find/primary/meta_test.go
cmd/internal/find/primary/numeric/predicate.go
cmd/internal/find/primary/parser.go
cmd/internal/find/primary/testdata/metadata.json

This commit adds support for predicate expressions to the `meta`
primary. Predicate expressions allow users to create more expressive
and powerful predicates. For example, the changes here reduce the
AWS reaper case from the verbose “-m .Tags[?].key termination_date -a -m .Tags[?].value +{1h}”
to the more expressive “-m .Tags[?] .key termination_date -a .value +{1h}”.
See the test cases in primary/meta_test.go for more examples.

Support predicate expressions in the `meta` primary

---

cmd/internal/find/parser/parse.go
cmd/internal/find/parser/parseOptions.go
cmd/internal/find/parser/parseOptions_test.go
cmd/internal/find/parser/parse_test.go
cmd/internal/find/primary/action.go
cmd/internal/find/primary/action_test.go
cmd/internal/find/primary/boolean.go
cmd/internal/find/primary/meta.go
cmd/internal/find/primary/meta_test.go
cmd/internal/find/primary/name.go
cmd/internal/find/primary/name_test.go
cmd/internal/find/primary/parser.go
cmd/internal/find/primary/parser_test.go
cmd/internal/find/primary/path.go
cmd/internal/find/primary/path_test.go
cmd/internal/find/primary/primary_test.go
cmd/internal/find/primary/size.go
cmd/internal/find/primary/size_test.go
cmd/internal/find/primary/timeAttr.go
cmd/internal/find/primary/timeAttr_test.go
cmd/internal/find/types/options.go
cmd/internal/find/walker.go

The meta primary's a specialized filter. This means that for a
given entry, it is unlikely that the entry's siblings or children
will have the same meta schema. Thus, it does not make sense for
`wash find` to recurse when the user specifies the meta primary
because recursing could lead to wasteful API requests.
Thus to avoid the unnecessary recursion, this commit sets the maxdepth
option to 1 if the meta primary's specified and the flag was not
provided on the command line.

 Default to maxdepth 1 if the meta primary is set 

---

cmd/server.go

They were "moved" in a prior commit, but I misunderstood how flags
worked and thought they'd be inherited. Restore them for the server.

Restore loglevel and logfile options for `wash server`

---

cmd/find.go
cmd/internal/find/main.go
cmd/internal/find/parser/parseExpression.go
cmd/internal/find/parser/parseOptions.go
cmd/internal/find/parser/parseOptions_test.go
cmd/internal/find/primary/action.go
cmd/internal/find/primary/boolean.go
cmd/internal/find/primary/meta.go
cmd/internal/find/primary/name.go
cmd/internal/find/primary/parser.go
cmd/internal/find/primary/parser_test.go
cmd/internal/find/primary/path.go
cmd/internal/find/primary/size.go
cmd/internal/find/primary/timeAttr.go
cmd/internal/find/types/options.go
cmd/internal/find/usage.go
cmd/list.go
cmd/ps.go
cmd/util/tables.go

This commit supports the help flags (-h/-help) for `wash find`.
Specifically, `wash find -h` outputs a general help message;
`wash find -h <primary>` outputs the detailed description of
the specified primary; while `wash find -h syntax` outputs
a detailed description of `wash find`'s expression syntax.

Generate help text for `wash find`

---

api/cache.go
api/exec.go
api/history.go
api/info.go
api/list.go
api/metadata.go
api/read.go
api/server.go
api/stream.go

Reduce logging redundancy by having the handler wrapper log start,
error, and complete for API requests.

Move common API logging to ServeHTTP handler

---

Dockerfile
README.md
activity/helper.go
docs/index.html
website/content/_index.md

Switch instructions to enter and exit `wash` rather than separately
start the server.
Update the Docker container to provide the same experience, and tweak
activity journals for the container process isolation model.

Update instructions around running Wash

---

api/exec.go
plugin/aws/ec2Instance.go
plugin/docker/container.go
plugin/execCommand.go
plugin/execCommandImpl.go
plugin/execCommandImpl_test.go
plugin/externalPluginEntry.go
plugin/kubernetes/pod.go
plugin/outputStream.go
plugin/outputStream_test.go
plugin/types.go
transport/ssh.go
volume/fs.go
volume/fs_test.go

This commit refactors Exec's plugin interface to be more plugin-author
friendly, and simpler to understand. It includes the following changes:
* Rename plugin.ExecResult => plugin.ExecCommand
plugin.ExecCommand better reflects what is being returned.
* Enforce a strict separation between what an Exec caller needs to care
about (plugin.ExecCommand) vs. what a plugin author needs to care about
(plugin.ExecCommandImpl) when implementing Exec
Exec callers should only care about a command's output channel and exit
code. They should not have to worry about context-cancellation cleanup
like ensuring that the command's stopped. That cleanup is the plugin
author's responsibility. On the other hand, it would be annoying for a
plugin author to have to remember to handle context-cancellation
cleanup. …

Refactor Exec's plugin interface

---

plugin/aws/s3Bucket.go

When making multiple requests to list the same S3 bucket, the first request would get the region and update the client to use that region but subsequent requests for the same path (but with new instances of the s3Bucket object) would use the cached region and not update the client. This resulted in lots of failures due to incorrect region after the first request. Fix so we always update the client to the correct region.

Fix AWS region on S3 buckets

---

README.md

Add section links - similar to the Wash website - to help navigate the
README.

Add section links to Wash README

---

plugin/externalPluginEntry.go
plugin/internal/command.go
plugin/types.go
website/static/docs/external_plugins/examples/sshfs.sh

 Support ExecOptions in external plugin exec

---

cmd/root.go
cmd/server.go

Bump default loglevel for the shell to warn so it's less verbose on
startup/shutdown.

Change 'wash' shell's default loglevel to warn

---

.gitattributes

Prior to this commit, github-linguist detects the repository language as
HTML. This commit adds a .gitattributes file with overrides for the
repository's top-level `docs` and `website` directories, so
github-linguist appropriately detects the language (as go).
Signed-off-by: Geoff Nichols <geoff.nichols@puppet.com>

Add .gitattributes file with github-linguist overrides

---

api/cache_test.go
api/helpers.go
api/helpers_test.go
api/list.go
fuse/core.go
fuse/dir.go
fuse/file.go
plugin/action.go
plugin/cache.go
plugin/cache_test.go
plugin/entryAttributes.go
plugin/entryBase.go
plugin/helpers.go
plugin/types.go
volume/fs_test.go

Latter's more general and is consistent with how we've been thinking
about "Group" entries throughout the code.

Rename "Group" => "Parent"

---

cmd/clear.go
cmd/ps.go
cmd/root.go
cmd/rootMain.go
cmd/tail.go

Attempt to shorten descriptions and sentences to fit better in an
80-character terminal and to use fewer lines. Makes the initial
experience prettier.

Tighten up wording and formatting

---

cmd/root.go
cmd/rootMain.go
cmd/tail.go
fuse/core.go

Fix an issue with OSXFUSE where the mountpoint doesn't correctly unmount introduced by #303. Also make FUSE server shutdown more deterministic to avoid shutdown races.
Defer to `/usr/bin/tail` for plain `tail` calls to make it more useful.
Add `-c` argument for Wash shell, primarily for debugging.

Fix FUSE, fallback to tail, and add '-c' argument for shell

---

fuse/core.go
fuse/dir.go

This type of filesystem activity is common and introduces lots of noise
in `wash history`. It's also rare that anyone except a Wash core
developer cares about these things. Exclude them from activity and log
directly to debug.
Fixes #323.

Exclude attribute and find logging from activity

---

cmd/stree.go
plugin/registry.go
plugin/schema.go

The Label's useful for stree. We previously defaulted to printing the
fully qualified type if Label was not provided, but there was no good
reason to do this.

Panic if EntrySchema#Label is not provided

---

plugin/execCommandImpl.go
plugin/types.go
volume/core.go
volume/dir.go
volume/dir_test.go
volume/fs.go
volume/fs_test.go
volume/stat.go
volume/stat_test.go

PR #330 introduced a regression where, when the cache expired, listing a volume could repopulate the cache with different data and break navigation. Fix so that VolumeList calls for a particular cache key always uses the same path.

Fix a regression introduced with volume improvements

---

cmd/clear.go
cmd/exec.go
cmd/history.go
cmd/info.go
cmd/internal/config/core.go
cmd/list.go
cmd/root.go
cmd/rootMain.go

When running in the `wash` shell, we alias several commands so they
don't override common shell builtins. However the `help` text wasn't
updated to reflect this, which can lead to unexpected errors like trying
to run `exec` and having it overwrite the shell process rather than
invoke a command on the target.
Update help output for aliased commands when run from within the shell
to refer to only command names that are setup in the shell.
Fixes #329.

Update help to match environment when running in wash shell

---

cmd/rootMain.go

Commands that are renamed to avoid colliding with builtins also have the
original names omitted when run in the wash shell. This is so their help
output is consistent within the shell. However that results in the
commands now erroring because the original command name is unknown.
Since the commands are renamed so they display correctly in help, have
the executable wrappers call to the changed name.

Fix aliased commands in wash shell

---

plugin/aws/ec2Instance.go
transport/ssh.go

Fixes a bug where setting User in .ssh/config wasn't working. 
Also extends the Identity type in transport/ssh.go. Currently, when using 'wash exec' on an ec2 instance, the hostname is derived automatically because it can be fetched from the instance metadata. Similarly, with these changes, the user often isn't required to define IdentityFile or User in ~/.ssh/config. The new fields in the Identity type are:
- IdentityFile. The ssh key name is fetched from metadata and appended to make an educated guess that the user's private key is ~/.ssh/keyname.pem
- FallbackUser, currently hardcoded to be the default user for Amazon Linux AMI instances, "ec2-user". (A further enhancement is planned to scrape the default user name from console output -- eg "centos" or "ubuntu" -- and use that for …

Bug fix setting ec2 User. Extend Identity type

---

docs/docs/index.html
plugin/externalPluginScript.go
website/content/docs/_index.md

Add notes about using Wash's loglevel and logfile to expose
plugin-related messages. Also include the output of running scripts.
Resolves #341.

Add notes on debugging during plugin development

---

.travis.yml

Detect when the website needs a rebuild via `hugo -s website` and fail
the build. Also fail if the website needs a clean rebuild because some
contents was removed.

Fail CI if the website has not been rebuilt

---

plugin/aws/ec2Instance.go
plugin/aws/ec2InstanceConsoleOutput.go

Scan console output for the user name that the ec2 instance was provisioned with. if none is found, set it to a best guess, "ec2-user".
A change to the method cachedConsoleOutput was also needed... Makes it a function of ec2Instance instead of ec2InstanceConsoleOutput.

Resolve Issue #348: Scrape user name from the ec2 console output

---

.travis.yml
cmd/validate.go
fuse/core.go
munge/mode.go
munge/mode_test.go
plugin/entryAttributes.go
plugin/entryAttributes_test.go
volume/fs.go
volume/stat.go
volume/stat_test.go

Fix symlinks so we get something usable. For now that means following symlinks for find/stat. Filed #378 to add representation of symlinks.
Fix mode serialization so we get the correct mode from the API. What we get from serializing an Entry now differs from what we get when requesting attributes/metadata; each uses a format that's appropriate for the use case (attributes/metadata gets a stringified representation similar to what `ls` outputs, Entries use the raw os.FileMode data). Find/stat now use a Tty when Wash does to better reflect the output a user would get when in a shell on the system. Mode is now included in `list` output.
Fix a few issues from `wash validate`:
- switch from TypeID to Label so we display something more human-readable
- wait for the progress writer to finish …

Fix file representation in volumes

---

api/cache_test.go
datastore/cache.go
datastore/cache_test.go
docs/docs/index.html
fuse/core.go
plugin/aws/ec2Instance.go
plugin/aws/ec2InstanceConsoleOutput.go
plugin/cache_test.go
plugin/docker/container-metadata.go
plugin/docker/container.go
plugin/helpers.go
plugin/kubernetes/pod.go
website/content/docs/_index.md

Previously an entry that didn't set its size would default to 0. Many common CLI tools will ignore an empty file rather than try to open it. Update to use a default of 4k, and when cached content is available use that to give a more accurate size. This allows plugin writers to only set the size when they actually know it without downloading the content.
Resolves #355.

Make setting size optional

---

api/error.go
api/helpers.go
api/helpers_test.go

When I wrote this I missed that there was already a method for
retrieving a single value for a query parameter. Use it instead of my
custom code.

Use Query Get method

---

.github/CODEOWNERS
CODEOWNERS

Switches from direct reference of team members to the team
@puppetlabs/wash.

Move CODEOWNERS to a more visible location and use team alias
