puppetlabs/wash

README.md, examples/swarm/Dockerfile, examples/swarm/app.py, examples/swarm/docker-compose.yml, examples/swarm/requirements.txt
Provide a short section walking through using wash with a multi-container Docker application.
=> Add a section to the README going through examples of using wash

api/client/client.go, cmd/clear.go, cmd/root.go, datastore/cache.go
=> Add `wash clear` for clearing cached data

README.md
=> Update README based on current features

cmd/find.go, cmd/find/booleanPrimary.go, cmd/find/grammar.go, cmd/find/namePrimary.go, cmd/find/parser.go, cmd/find/parser_test.go, cmd/find/timeAttrPrimary.go, cmd/find/timeAttrPrimary_test.go
=>  Add primaries for the ctime, mtime, and atime attributes

cmd/tail.go
Cleanup tail implementation to be more readable and attempt to open each
file in the order they're listed. Extracts attempting to tail streaming
and file entries to functions.
=> Simplify tail implementation

cmd/find.go, cmd/find/booleanPrimary.go, cmd/find/entry.go, cmd/find/grammar.go, cmd/find/main.go, cmd/find/namePrimary.go, cmd/find/namePrimary_test.go, cmd/find/parser.go, cmd/find/parser_test.go, cmd/find/pathPrimary.go, cmd/find/pathPrimary_test.go, cmd/find/sizePrimary.go, cmd/find/sizePrimary_test.go, cmd/find/timeAttrPrimary.go, cmd/find/timeAttrPrimary_test.go
=>  Implement depth-first recursion in `wash find` + path primary

api/client/client.go, api/fs/core.go, api/fs/dir.go, api/fs/file.go, api/helpers.go, cmd/internal/find/clientWrappers.go, cmd/internal/find/main.go, cmd/internal/find/walker.go, cmd/tail.go, plugin/aws/ec2InstanceConsoleOutput.go, plugin/aws/ec2InstanceMetadataJSON.go, plugin/docker/container-log.go, plugin/docker/container-metadata.go, plugin/docker/container.go, plugin/entryAttributes.go, plugin/entryAttributes_test.go, plugin/entryBase.go
=> Extract client to interface; re-define meta + simplify plugins; fix bug in apifs

api/types/error.go
=> Add code documentation to clarify how Error() for ErrorObj is used

docs/404.html, docs/categories/index.html, docs/index.html, docs/tags/index.html, website/config.toml
Signed-off-by: Deepak Giridharagopal <deepak@puppet.com>
=> Fix website link to slack channel

api/exec.go, api/list.go, api/read.go, api/stream.go, cmd/internal/find/primary/action.go, cmd/internal/find/primary/action_test.go, cmd/internal/find/primary/meta/numericPredicate.go, cmd/internal/find/primary/meta/timePredicate.go, cmd/internal/find/primary/meta/timePredicate_test.go, cmd/internal/find/primary/numeric/bracket.go, cmd/internal/find/primary/numeric/bracket_test.go, cmd/internal/find/primary/numeric/sign.go, cmd/internal/find/primary/numeric/sign_test.go, cmd/internal/find/walker.go, cmd/list.go, fuse/core.go, fuse/dir.go, fuse/file.go, plugin/action.go
=> Add action primary; return false for time-mismatches in TimePredicate

docs/custom.css, docs/index.html, docs/index.xml, website/content/_index.md, website/static/custom.css
=> Reorganize site content, add TOC-style links

cmd/internal/find/parser/expression/atom.go, cmd/internal/find/parser/expression/error.go, cmd/internal/find/parser/expression/parser.go, cmd/internal/find/parser/parseExpression_test.go, cmd/internal/find/parser/parsertest/suite.go, cmd/internal/find/primary/meta.go, cmd/internal/find/primary/meta/arrayPredicate.go, cmd/internal/find/primary/meta/arrayPredicate_test.go, cmd/internal/find/primary/meta/expression.go, cmd/internal/find/primary/meta/oaPredicate.go, cmd/internal/find/primary/meta/objectPredicate.go, cmd/internal/find/primary/meta/objectPredicate_test.go, cmd/internal/find/primary/meta/predicateExpression.go, cmd/internal/find/primary/meta/predicateExpression_test.go, cmd/internal/find/primary/meta/predicate_test.go, cmd/internal/find/primary/meta/primitivePredicate_test.go, cmd/internal/find/primary/meta/timePredicate_test.go, cmd/internal/find/primary/meta_test.go, cmd/internal/find/primary/timeAttr_test.go
=> Support predicate expressions in ObjectPredicate/ArrayPredicate

docs/index.html, website/content/_index.md
=> Fix broken link to website README

plugin/aws/profile.go
Distinguish between prompts for different profiles in case there are
several.
=> Provide custom prompt for each profile

plugin/externalPluginEntry.go, plugin/externalPluginScript.go, plugin/helpers.go, plugin/helpers_test.go
Resolves https://github.com/puppetlabs/wash/issues/231
=> Cleanup orphaned processes in external plugin exec

api/client/client.go
In practice running `wash history` still creates an entry in history
from filesystem interaction, and the API handler writes messages that
currently go to the dead letter office.
Simplify the client implementation for history by using a common request
helper that no longer requires the `path` argument. Include history in
itself.
=> Refactor API client

plugin/action.go, plugin/entryAttributes.go, plugin/externalPluginEntry.go, plugin/externalPluginEntry_test.go, plugin/externalPluginRoot.go, plugin/externalPluginRoot_test.go, plugin/externalPluginScript.go, plugin/helpers.go, plugin/internal/command.go, plugin/testdata/external.sh, website/static/docs/external_plugins/examples/sshfs.sh
=> Update the external plugin interface with the recent changes

plugin/externalPluginRoot_test.go, plugin/helpers.go
=> Remove unnecessary errors; run external plugin root tests

README.md, cmd/clear.go, cmd/exec.go, cmd/history.go, cmd/info.go, cmd/list.go, cmd/meta.go, cmd/ps.go, cmd/root.go, cmd/rootMain.go, cmd/server.go, cmd/tail.go, docs/docs/index.html, docs/index.html, website/content/_index.md, website/content/docs/_index.md
=> Reorganize README and website, improve command help

cmd/internal/find/parser/parseExpression_test.go, cmd/internal/find/parser/parseOptions_test.go, cmd/internal/find/parser/parsertest/suite.go, cmd/internal/find/primary/action_test.go, cmd/internal/find/primary/meta/arrayPredicate_test.go, cmd/internal/find/primary/meta/emptyPredicate_test.go, cmd/internal/find/primary/meta/numericPredicate_test.go, cmd/internal/find/primary/meta/objectPredicate_test.go, cmd/internal/find/primary/meta/predicateExpression_test.go, cmd/internal/find/primary/meta/predicate_test.go, cmd/internal/find/primary/meta/primitivePredicate_test.go, cmd/internal/find/primary/meta/stringPredicate_test.go, cmd/internal/find/primary/meta/timePredicate_test.go, cmd/internal/find/primary/meta_test.go, cmd/internal/find/primary/name_test.go, cmd/internal/find/primary/parser_test.go, cmd/internal/find/primary/path_test.go, cmd/internal/find/primary/primary_test.go, cmd/internal/find/primary/size_test.go, cmd/internal/find/primary/timeAttr_test.go
This makes tests easier to write and less verbose.
=> Refactor `wash find`'s test suite

cmd/internal/find/parser/parseExpression.go, cmd/internal/find/primary/meta.go, cmd/internal/find/walker.go, cmd/meta.go, docs/docs/index.html, website/content/docs/_index.md
=> Fix bug in `wash find` + add attribute flag to `wash meta`

plugin/kubernetes/pod.go
These were overlooked during the Exec plugin interface refactor
Resolves https://github.com/puppetlabs/wash/issues/293
=> Fix Kubernetes pod exec by setting exit code + exit error

README.md, docs/index.html, website/content/_index.md
Incorporates new improvements to wash, and tightens up the timing and
content (primarily removes `wash history`, as it's hard to follow in
this format).
=> Use a new, shorter asciicast

docs/docs/external_plugins/index.html, docs/docs/index.html, website/content/docs/_index.md, website/content/docs/external_plugins/_index.md
=> Provide an example of the passed-in path for external plugins

cmd/rootMain.go, website/content/docs/_index.md
=> Provide workaround for running multiple Wash shells

cmd/clear.go, cmd/exec.go, cmd/find.go, cmd/history.go, cmd/info.go, cmd/internal/cmdtest/client.go, cmd/internal/cmdtest/suite.go, cmd/internal/find/main.go, cmd/internal/find/main_test.go, cmd/internal/find/primary/parser.go, cmd/internal/find/walker.go, cmd/internal/find/walker_test.go, cmd/list.go, cmd/meta.go, cmd/ps.go, cmd/rootMain.go, cmd/tail.go, cmd/util/client.go, cmd/util/format.go, cmd/version.go
=> Add unit tests for `wash find`'s walker + main function

activity/core.go, datastore/cache.go, datastore/cache_test.go, transport/ssh.go
=> Limit open journals to avoid running out of file descriptors

api/helpers_test.go, cmd/internal/server/core.go, cmd/rootMain.go, cmd/server.go, docs/docs/external_plugins/index.html, docs/docs/index.html, docs/index.html, plugin/aws/root.go, plugin/docker/root.go, plugin/externalPluginRoot.go, plugin/externalPluginRoot_test.go, plugin/externalPluginScript.go, plugin/kubernetes/root.go, plugin/registry.go, plugin/registry_test.go, plugin/testdata/external.sh, plugin/types.go, website/content/docs/_index.md, website/content/docs/external_plugins/_index.md
Support plugin-specific config (#289) and use it to allow configuring which AWS profiles are available (#317).
=> Support plugin-specific config and limiting AWS profiles

api/client/client.go, api/fs/core.go, api/fs/dir.go, api/fs/file.go, api/helpers.go, api/types/schema.go, cmd/internal/cmdtest/client.go, cmd/root.go, cmd/rootMain.go, cmd/stree.go, go.mod, go.sum, plugin/aws/ec2Instance.go, plugin/docker/container.go, plugin/docker/containersDir.go, volume/fs.go
=> Add the stree command

cmd/internal/server/core.go, cmd/rootMain.go, cmd/server.go, docs/docs/index.html, go.mod, plugin/externalPluginRoot.go, plugin/externalPluginSpec.go, plugin/externalPluginSpec_test.go, plugin/registry.go, plugin/registry_test.go, website/content/docs/_index.md
=> Add option to configure enabled core plugins

api/list.go, cmd/history.go, go.mod, go.sum, plugin/aws/ec2Instance.go, plugin/docker/container.go, plugin/docker/volume.go, plugin/kubernetes/pvc.go, volume/core.go, volume/dir.go, volume/dir_test.go, volume/file_test.go, volume/fs.go, volume/fs_test.go, volume/stat.go, volume/stat_test.go
=> Explore volumes incrementally, sort API list response, make history entry more readable

docs/docs/core_plugins/index.html, transport/ssh.go, website/content/docs/core_plugins/_index.md
Updated to provide useful context for working on existing plugins as
well as how to start a new one.
=> Update core plugin docs to provide more complete explanations

plugin/aws/ec2Instance.go, transport/ssh.go
=> Cleanup style issues from #335

api/schema.go
=> Check for nil schema in /fs/schema before filling it in

plugin/docker/volume.go
Previously cleanup would fail if we did it after the context was
cancelled because we would pass a cancelled context to the cleanup
functions. Pass a new context to them to ensure they run.
Also fix VolumeStream, which never worked.
Fixes #370.
=> Fix Docker cleanup when context is cancelled and VolumeStream

api/schema.go, api/types/entrySchema.go, api/types/testdata/invalidSchema.json, api/types/testdata/validSchema.json, cmd/internal/find/types/testdata/complex.json, cmd/internal/find/types/testdata/metadata.json, cmd/internal/find/types/testdata/real_world_aws.json, cmd/internal/find/types/testdata/tree.json, cmd/internal/find/types/testdata/triangle.json, plugin/entrySchema.go, plugin/externalPluginEntry.go, plugin/externalPluginEntry_test.go, plugin/externalPluginRoot.go, plugin/externalPluginRoot_test.go, plugin/externalPluginScript.go, plugin/registry.go, plugin/testdata/externalPluginSchema.json, plugin/testdata/externalPluginSchema_PartitionedSchemaGraph.json, plugin/testdata/externalPluginSchema_SchemaGraph.json
=>  Support external plugin schemas

plugin/externalPluginEntry.go, plugin/externalPluginEntry_test.go, plugin/externalPluginRoot_test.go, plugin/testdata/externalPluginSchema.json
=> Don't require type ID + continue supporting empty methods array

api/types/entrySchema.go, api/types/entrySchema_test.go, cmd/internal/find/primary/meta.go, cmd/internal/find/types/entrySchema.go, cmd/internal/find/walker.go, docs/docs/core_plugins/index.html, docs/docs/external_plugins/index.html, docs/docs/index.html, docs/index.html, plugin/entrySchema.go, plugin/externalPluginEntry.go, plugin/externalPluginEntry_test.go, plugin/helpers.go, plugin/types.go, volume/fs.go, website/content/docs/_index.md, website/content/docs/core_plugins/_index.md, website/content/docs/external_plugins/_index.md
Resolves https://github.com/puppetlabs/wash/issues/365
=>  Update docs with the entry schema changes

.github/CODEOWNERS, README.md, docs/index.html, website/content/_index.md
Separates goals of our website and github README. Website serves as an introduction for those interested in using and extending Wash, README is focused on development.
Rearranges and updates the introduction to focus a little more on what people might accomplish with Wash.
Improve the getting started section on the website.
Resolves #381.
=> Improve documentation structure

README.md
=> Mark plugin configuration enhancement as complete
